version: '3.8'

services:
  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike-server
    networks:
      - aerospike_net
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    environment:
      - CONFIG_FILE=/opt/aerospike/etc/aerospike.conf
    volumes:
      - ./aerospike.conf:/opt/aerospike/etc/aerospike.conf

networks:
  aerospike_net:
    driver: bridge
